[Task VM-30] [Petkata] Putting PasswordHasher
NDecheva/VacationsManager pull request #15
Opened 2024-11-21 18:03 UTC by Petkata23

2024-11-21 18:13 UTC, ectky requested changes

2024-11-21 18:13 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/VacationsManagerDbContext.cs
> -            modelBuilder.Entity<VacationRequest>()
защо тези поправки излизат тук? Нали ги мърджна в мейн

2024-11-21 18:13 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
Къде се ползва хешъра?

2024-11-21 18:17 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Data/VacationsManagerDbContext.cs
> -            modelBuilder.Entity<VacationRequest>()
Защото днеска правихме всичко на веднъж и PasswordHashera се беше base-нал на бранча с DbContexta. В момента направих промените и тук за да не ви отварям работа да resolve-вате конфликти :D

2024-11-21 18:19 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
Нали трябва да си е в Security?

2024-11-21 18:20 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
Гледал съм го от общия

2024-11-21 18:21 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/VacationsManagerDbContext.cs
> -            modelBuilder.Entity<VacationRequest>()
Ти трябваше да си резолвнеш конфликтите с мейн.
git checkout main
git fetch
git pull
git checkout твоя-бранч
git rebase main

2024-11-21 18:21 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
Ама къде ще го ползваш?

2024-11-21 18:23 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
Трябва за единия метод на User репозиторито. Ние днеска всичко го правихме по хронология. Каквото трябва сме го слагали първо и така

2024-11-21 18:23 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Data/VacationsManagerDbContext.cs
> -            modelBuilder.Entity<VacationRequest>()
Ок но не става ли и така?

2024-11-21 18:25 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
На още едно място се ползва.

2024-11-21 18:26 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/VacationsManagerDbContext.cs
> -            modelBuilder.Entity<VacationRequest>()
Пробвай сега да го направиш. Понякога се обърква гит-а.

2024-11-21 18:26 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
Добре но не сме стигнали до там. Нали в момента пускам рекуест просто да го добавя?

2024-11-21 18:27 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Data/VacationsManagerDbContext.cs
> -            modelBuilder.Entity<VacationRequest>()
Кое да направя?

2024-11-21 18:27 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
Ама пропуснали сте го. Затова те питам.

2024-11-21 18:27 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/VacationsManagerDbContext.cs
> -            modelBuilder.Entity<VacationRequest>()
git checkout main
git fetch
git pull
git checkout твоя-бранч
git rebase main

2024-11-21 18:28 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Data/VacationsManagerDbContext.cs
> -            modelBuilder.Entity<VacationRequest>()
Значи да hard ресетна комита за фикса? И после да го направя

2024-11-21 18:29 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
Смисъл? Къде сме го пропуснали?

2024-11-21 18:30 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/VacationsManagerDbContext.cs
> -            modelBuilder.Entity<VacationRequest>()
Не, просто си рибейсни бранча към мейн. Само тези команди трябва да изпълниш.

2024-11-21 18:32 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Data/VacationsManagerDbContext.cs
> -            modelBuilder.Entity<VacationRequest>()
готово

2024-11-21 18:35 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Data/VacationsManagerDbContext.cs
> -            modelBuilder.Entity<VacationRequest>()
Sync-нах след това и пушнах. Нали така трябва?

2024-11-21 18:42 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/VacationsManagerDbContext.cs
> -            modelBuilder.Entity<VacationRequest>()
топ

2024-11-22 07:45 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
Unbelievable госпожо, че съм го пропуснал в dbcontexta, сега като се замислих и се сетих хахаха. Това вчера от бързане 😂

2024-11-22 07:47 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
И междодругото вчера като се пробвах да правя миграциите се правят, но когато стартна проекта изписва странна грешка в конзолата, която така и не можах да я оправя. Всичко си има в program.cs, connection-а е ок, но не знам. Дори не иска да създава базата.

2024-11-22 07:48 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
Направил съм отделен бранч за миграциите в който са в момента

2024-11-22 07:48 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
Пиши после в сървъра и прати грешката да я видя.

2024-11-22 07:50 UTC, Petkata23 commented
Ей сега след голямото ще си взема лаптопа от вкъщи и ще почна да гледам нещата. И без това имаме 3 часа при Дечева

2024-11-22 07:51 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
Не ми resolve-вай коментарите плс :Д

2024-11-22 07:52 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Shared/Security/PasswordHasher.cs
> +    public static class PasswordHasher
Не съм

2024-11-22 09:28 UTC, ectky approved these changes

2024-11-22 09:33 UTC, merged