VM-33 VM-43 Created services and repos tests
NDecheva/VacationsManager pull request #21
Opened 2024-11-28 11:11 UTC by krisilozeva

2024-11-28 11:15 UTC, Petkata23 requested changes

2024-11-28 11:15 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManager.Services/RoleService.cs
> +
Ролята задължителна моля :Д

2024-11-28 11:18 UTC, Petkata23 approved these changes

2024-12-02 07:12 UTC, ectky requested changes
Защо пак всичко е в един пул рекуест?

2024-12-02 07:12 UTC, ectky commented on VacationsManagerMVC/VacationManager.Tests/Repos/BaseRepositoryTests.cs
> +    public abstract class BaseRepositoryTests<TRepository, T, TModel>
Колко е code coverage-a на репотата?

2024-12-03 09:07 UTC, closed without merging