VM-39 Ilian crudcontrollers
NDecheva/VacationsManager pull request #32
Opened 2024-12-10 10:57 UTC by ilian920

Make a controllers

2024-12-10 11:04 UTC, Petkata23 submitted a review, later dismissed

2024-12-10 12:01 UTC, Petkata23 requested changes

2024-12-10 12:01 UTC, Petkata23 commented on VacationsManagerMVC/VacationsManagerMVC/Controllers/NotificationController.cs
> +    public class NotificationController : BaseCrudController<NotificationDto, INotificationRepository, INotificationService, NotificationEditVM, NotificationDetailsVM>
трябва да се промени Athorize-ът на всички контролери с правилните стойности от enum-а

2024-12-10 12:14 UTC, Petkata23 approved these changes

2024-12-20 08:14 UTC, ectky approved these changes

2024-12-20 08:15 UTC, merged