[Task VM-23 and VM-27] Created Entities, IBaseRepository and BaseRepository
NDecheva/VacationsManager pull request #5
Opened 2024-11-15 12:37 UTC by Petkata23

2024-11-19 13:00 UTC, ectky requested changes

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/Notification .cs
> +        public User Recipient { get; set; }
къде е foreign key-a за това свойство, също външните свойства трябва да са virtual

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/Notification .cs
> +            Message = string.Empty;
какво ще стане с message-a ако се ползва този конструктор?

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/Notification .cs
> +            DateSent = DateTime.UtcNow;
тези свойства вече се попълват от базовия конструктор

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/Notification .cs
> +            IsRead = false;
тези свойства вече се попълват от базовия конструктор

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/Project .cs
> +            Teams = new List<Team>();
тези свойства вече се попълват от базовия конструктор

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/Role .cs
> +            Users = new List<User>();
тези свойства вече се попълват от базовия конструктор

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/Team .cs
> +        public virtual Project Project { get; set; }
къде е foreign key-a за това свойство

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/Team .cs
> +        public virtual User TeamLeader { get; set; }
къде е foreign key-a за това свойство

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/Team .cs
> +            Developers = new List<User>();
тези свойства вече се попълват от базовия конструктор

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/User .cs
> +        public int? RoleId { get; set; }
може ли потребител без роля?

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/User .cs
> +        public User(string username, string password, string firstName, string lastName, Role role = null, Team team = null)
защо са ти тези конструктори, махни ги от всички ентитита

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/VacationRequest .cs
> +        public DateTime CreationDate { get; set; }
BaseEntity няма ли вече такова свойство?

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/VacationRequest .cs
> +        public User Requester { get; set; }
къде е foreign key-a за това свойство, също външните свойства трябва да са virtual

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/VacationRequest .cs
> +        public VacationRequest(DateTime startDate, DateTime endDate, User requester, bool isHalfDay, bool isSickLeave, string attachment = null)
🗑️

2024-11-19 13:00 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/VacationRequest .cs
> +        public VacationRequest()
🗑️

2024-11-20 08:01 UTC, ectky requested changes

2024-11-20 08:01 UTC, ectky commented on VacationsManagerMVC/VacationsManager.Data/Entities/VacationRequest .cs
> +        public DateTime CreationDate { get; set; } = DateTime.UtcNow;
нали в base entity има Created защо тук пак

2024-11-20 08:36 UTC, ectky requested changes
имаш неоправени коментари

2024-11-20 08:40 UTC, Petkata23 commented
Къде?

2024-11-20 08:40 UTC, ectky commented
тук

2024-11-20 08:45 UTC, ectky approved these changes

2024-11-20 16:54 UTC, merged